apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-eden-api
  labels:
    run: api
  namespace: webapi
spec:
  selector:
    matchLabels:
      run: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - name: api
        image: us.gcr.io/new-eden-storage-a5c23/chingy-webapi:v1.109
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  name: api-service
  namespace: webapi
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    run: api
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: new-eden-tls
  namespace: webapi
spec:
  domains:
    - api.new-eden.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    networking.gke.io/managed-certificates: new-eden-tls
    kubernetes.io/ingress.global-static-ip-name: new-eden-ip
  name: new-eden-ingress
  namespace: webapi
spec:
  defaultBackend:
    service:
      name: api-service
      port:
        number: 8000
